version: '3'

services:
  chain:
    restart: always
    image: ${repo_url}/${app}:${tag}
    container_name: "chain"
    env_file:
      - ".env"
    ports:
      - "18545:18545"
      - "10303:10303"
      - "10303:10303/udp"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/:/root/.dpeth

    # for masternode use
    #entrypoint: 
    #  - bash 
    #  - -c
    #  - |
    #    /app/init.sh && /app/${app} --syncmode 'full' --rpc --rpcaddr localhost --rpcport 18545 --rpccorsdomain '*' --rpcapi 'personal,db,eth,net,web3,txpool,miner,net,admin' --bootnodes "${bootnode}" --mine --port 10303 -unlock '${your miner address}' --password /root/.dpeth/pass --etherbase "${your miner address}" --verbosity 5

    # for common node use.
    entrypoint: 
       - bash 
       - -c
       - |
         /app/init.sh && /app/${app} --syncmode 'full' --rpc --rpcaddr 0.0.0.0 --rpcport 18545 --rpccorsdomain '*' --rpcvhosts '*' --rpcapi 'eth,net,txpool' --bootnodes "${bootnode}" --port 10303  --verbosity 5
